aroundfloor:
  # 可視化範囲（ブロック単位）
  visibility-range: 10
  # 対象Y座標範囲
  source-y-min: -50
  source-y-max: -10
  # 表示Y座標範囲
  display-y-min: 50
  display-y-max: 90
  # Y座標オフセット
  y-offset: 100
  # 更新間隔（tick）
  update-interval: 20
  # デバッグモード
  debug: false 